/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocofinal;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andrea
 */
public class borsa extends javax.swing.JFrame {

    public void leggifile() {
        
        
        try {
            Scanner scan = new Scanner (new File ("pozionen.txt")); 
            while (scan.hasNextLine()) {
                String linea = scan.nextLine();
                 jLabel5.setText(linea);
               
                
            }    
    }   catch (FileNotFoundException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Scanner scan = new Scanner (new File ("superpozione.txt")); 
            while (scan.hasNextLine()) {
                String linea = scan.nextLine();
                 jLabel4.setText(linea);
               
                
            }    
    }   catch (FileNotFoundException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Scanner scan = new Scanner (new File ("iperpozione.txt")); 
            while (scan.hasNextLine()) {
                String linea = scan.nextLine();
                 jLabel6.setText(linea);
               
                
            }    
    }   catch (FileNotFoundException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Scanner scan = new Scanner (new File ("pozionemax.txt")); 
            while (scan.hasNextLine()) {
                String linea = scan.nextLine();
                 jLabel7.setText(linea);
               
                
            }    
    }   catch (FileNotFoundException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Creates new form borsa
     */
    public borsa() {
        initComponents();
        setLocationRelativeTo(null);
        jButton6.setEnabled(false);
         jButton7.setEnabled(false);
         
         leggifile();
         String tmp;
         
         tmp = jLabel5.getText();
         int pozione = Integer.parseInt(tmp);
         tmp = jLabel4.getText();
         int superpozione = Integer.parseInt(tmp);
         tmp = jLabel6.getText();
         int iperpozione = Integer.parseInt(tmp);
         tmp = jLabel7.getText();
         int pozionemax = Integer.parseInt(tmp);
         
         if (pozione == 0) {
             jButton2.setEnabled(false);
             
         }
         
         if (superpozione == 0) {
             jButton3.setEnabled(false);
             
         }
         
         if (iperpozione == 0) {
             jButton4.setEnabled(false);
             
         }
         
         if (pozionemax == 0) {
             jButton5.setEnabled(false);
             
         }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 770));
        setPreferredSize(new java.awt.Dimension(700, 770));
        setSize(new java.awt.Dimension(700, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("0");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 100, 40));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("0");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 90, 40));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 90, 40));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 100, 60));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 70, 50));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 80, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/aaaa.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 390, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/eteremax.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/etere.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/pozionemax.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/iperpozione.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/superpozione.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/pozione.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/indietro.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 660, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/arancione.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sfondosu.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("pozione.txt")) {
                scrivi.write("pozione");
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int attuale = Integer.parseInt(jLabel5.getText());
            System.out.println(attuale-1);
        try(FileWriter scrivi = new FileWriter ("pozionen.txt")) {
            String c = attuale-1 + "";
                scrivi.write(c);
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("pozione.txt")) {
                scrivi.write("superpozione");
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int attuale = Integer.parseInt(jLabel4.getText());
            System.out.println(attuale-1);
        try(FileWriter scrivi = new FileWriter ("superpozione.txt")) {
            String c = attuale-1 + "";
                scrivi.write(c);
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("pozione.txt")) {
                scrivi.write("iperpozione");
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         int attuale = Integer.parseInt(jLabel6.getText());
            System.out.println(attuale-1);
        try(FileWriter scrivi = new FileWriter ("iperpozione.txt")) {
            String c = attuale-1 + "";
                scrivi.write(c);
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("pozione.txt")) {
                scrivi.write("pozionemax");
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int attuale = Integer.parseInt(jLabel7.getText());
            System.out.println(attuale-1);
        try(FileWriter scrivi = new FileWriter ("pozionemax.txt")) {
            String c = attuale-1 + "";
                scrivi.write(c);
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("pozione.txt")) {
                scrivi.write("etere");
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("pozione.txt")) {
                scrivi.write("eteremax");
        } catch (IOException ex) {
            Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
