/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocofinal;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author andrea
 */
public class format2 extends javax.swing.JFrame {

    /**
     * Creates new form format
     */
    public format2() {
        initComponents();
        setLocationRelativeTo(null);
        formatta();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(693, 750));
        setSize(new java.awt.Dimension(693, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/annullaformat.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 650, 530, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/formattaperdavvero.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/cont.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 680, 180, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/ann.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 680, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/vers.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/warning.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/Formattazione.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/formatwarning.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/impostazioni.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/impostazioni.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new format().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try {
            Scanner ling = new Scanner (new File("defaultFile/lingua-def.txt"));
            while(ling.hasNextLine()) {
                String lingua = ling.nextLine();
                System.out.println(lingua);
                
                 try (FileWriter scrivi = new FileWriter ("lingua.txt")) {
                     scrivi.write(lingua);
            
            
        } catch (IOException ex) {
            Logger.getLogger(audio.class.getName()).log(Level.SEVERE, null, ex);
        }
                
            }
        } catch (FileNotFoundException ex) {
            System.out.println("File Non trovato");
        }
        
        try {
            Scanner ling = new Scanner (new File("defaultFile/sound-def.txt"));
            while(ling.hasNextLine()) {
                String lingua = ling.nextLine();
                System.out.println(lingua);
                
                 try (FileWriter scrivi = new FileWriter ("sound.txt")) {
                     scrivi.write(lingua);
            
            
        } catch (IOException ex) {
            Logger.getLogger(audio.class.getName()).log(Level.SEVERE, null, ex);
        }
                
            }
        } catch (FileNotFoundException ex) {
            System.out.println("File Non trovato");
        }
        
        try {
            Scanner ling = new Scanner (new File("defaultFile/profili-def.txt"));
            while(ling.hasNextLine()) {
                String lingua = ling.nextLine();
                System.out.println(lingua);
                
                 try (FileWriter scrivi = new FileWriter ("profili.txt")) {
                     scrivi.write(lingua);
            
            
        } catch (IOException ex) {
            Logger.getLogger(audio.class.getName()).log(Level.SEVERE, null, ex);
        }
                
            }
        } catch (FileNotFoundException ex) {
            System.out.println("File Non trovato");
        }
        
        try(FileWriter scrivi = new FileWriter ("punti.txt")) {
                    
                   
                            scrivi.write("0");
                    } catch (IOException ex) {
                        Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
        
        AudioPlayer.stop();
        this.setVisible(false);
        new menu().setVisible(true);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public void formatta() {
    TimerTask task = new TimerTask() {
        public void run() {
            System.out.println("Task performed on: " + new Date() + "n" +
              "Thread's name: " + Thread.currentThread().getName());
            
            jButton4.setIcon(new ImageIcon(getClass().getResource("formatta.png")));
        }
    };
    Timer timer = new Timer("Timer");
    
    long delay = 1500L;
    timer.schedule(task, delay);
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(format2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(format2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(format2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(format2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new format2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
