/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocofinal;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author andrea
 */
public class lott extends javax.swing.JFrame {

    /**
     * Creates new form lott
     */
    public lott() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
            Scanner scan = new Scanner (new File ("selected.txt")); 
            while (scan.hasNextLine()) {
                String linea = scan.nextLine();
                jLabel2.setIcon(new ImageIcon(getClass().getResource(linea+"-lott.png")));
                if (linea.equals("Garchomp")) {
                    jButton2.setIcon(new ImageIcon(getClass().getResource("terremoto.png")));
                    jButton3.setIcon(new ImageIcon(getClass().getResource("fossa.png")));
                    jButton4.setIcon(new ImageIcon(getClass().getResource("azione.png")));
                    jButton5.setIcon(new ImageIcon(getClass().getResource("rapido.png")));
                }
                
                if (linea.equals("Pikachu")) {
                    jButton2.setIcon(new ImageIcon(getClass().getResource("tuono.png")));
                    jButton3.setIcon(new ImageIcon(getClass().getResource("fulmine.png")));
                    jButton4.setIcon(new ImageIcon(getClass().getResource("azione.png")));
                    jButton5.setIcon(new ImageIcon(getClass().getResource("rapido.png")));
                }
                
                if (linea.equals("Zeraora")) {
                    jButton2.setIcon(new ImageIcon(getClass().getResource("tuono.png")));
                    jButton3.setIcon(new ImageIcon(getClass().getResource("fulmine.png")));
                    jButton4.setIcon(new ImageIcon(getClass().getResource("azione.png")));
                    jButton5.setIcon(new ImageIcon(getClass().getResource("comete.png")));
                }
                if (linea.equals("Charizard")) {
                    jButton2.setIcon(new ImageIcon(getClass().getResource("lanciafiamme.png")));
                    jButton3.setIcon(new ImageIcon(getClass().getResource("braciere.png")));
                    jButton4.setIcon(new ImageIcon(getClass().getResource("azione.png")));
                    jButton5.setIcon(new ImageIcon(getClass().getResource("comete.png")));
                }
                if (linea.equals("Blastoise")) {
                    jButton2.setIcon(new ImageIcon(getClass().getResource("pistola.png")));
                    jButton3.setIcon(new ImageIcon(getClass().getResource("bolle.png")));
                    jButton4.setIcon(new ImageIcon(getClass().getResource("azione.png")));
                    jButton5.setIcon(new ImageIcon(getClass().getResource("comete.png")));
                }
                
                if (linea.equals("Dragonite")) {
                    jButton2.setIcon(new ImageIcon(getClass().getResource("aero.png")));
                    jButton3.setIcon(new ImageIcon(getClass().getResource("raffica.png")));
                    jButton4.setIcon(new ImageIcon(getClass().getResource("azione.png")));
                    jButton5.setIcon(new ImageIcon(getClass().getResource("rapido.png")));
                }
                
            }
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 773));
        setPreferredSize(new java.awt.Dimension(700, 773));
        setSize(new java.awt.Dimension(700, 773));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, -1, -1));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/indietro.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 660, 120, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/lottasfondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sfondosu.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("mossa.txt")) {
                   
                            scrivi.write("terremoto");
                    } catch (IOException ex) {
                        Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
                    }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("mossa.txt")) {
                   
                            scrivi.write("fossa");
                    } catch (IOException ex) {
                        Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
                    }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("mossa.txt")) {
                   
                            scrivi.write("azione");
                    } catch (IOException ex) {
                        Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
                    }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try(FileWriter scrivi = new FileWriter ("mossa.txt")) {
                   
                            scrivi.write("rapido");
                    } catch (IOException ex) {
                        Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
                    }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lott().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
