/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocofinal;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author andrea
 */
public class profilo extends javax.swing.JFrame {

    private String nomev = "";
    private String compleannov = "" ;
    private String areav = "";
    /**
     * Creates new form format
     */
    public profilo() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        try (Scanner scan = new Scanner (new File ("profili.txt"))) {
            while(scan.hasNextLine()) {
                String riga = scan.nextLine();
                String[] contenuto = riga.split(" ");
                
               
                
                this.nomev = contenuto[0];
                this.compleannov = contenuto[1];
                this.areav = contenuto[2];
                
                //System.out.println(nomev + compleannov + areav);
                nome.setText(nomev);
                compleanno.setText(compleannov);
                area.setText(areav);
            }
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(profilo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area = new javax.swing.JLabel();
        compleanno = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        deu1 = new javax.swing.JButton();
        ita = new javax.swing.JButton();
        eng = new javax.swing.JButton();
        deu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(693, 750));
        setSize(new java.awt.Dimension(693, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        area.setText("Italia");
        getContentPane().add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        compleanno.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        compleanno.setText("12/03");
        getContentPane().add(compleanno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        nome.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        nome.setText("Andrea");
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        deu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/residenza.png"))); // NOI18N
        deu1.setContentAreaFilled(false);
        deu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deu1ActionPerformed(evt);
            }
        });
        getContentPane().add(deu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 420, 80));

        ita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/nickname.png"))); // NOI18N
        ita.setContentAreaFilled(false);
        ita.setEnabled(false);
        ita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itaActionPerformed(evt);
            }
        });
        getContentPane().add(ita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 420, 80));

        eng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/compleanno.png"))); // NOI18N
        eng.setContentAreaFilled(false);
        eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engActionPerformed(evt);
            }
        });
        getContentPane().add(eng, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 420, 80));

        deu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/cambiautente.png"))); // NOI18N
        deu.setContentAreaFilled(false);
        deu.setEnabled(false);
        deu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deuActionPerformed(evt);
            }
        });
        getContentPane().add(deu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 420, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/ok.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 680, 180, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/annulla.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 680, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/profilo_.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/impostazioni.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/impostazioni.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try (FileWriter scrivi = new FileWriter("profili.txt")) {
            
            scrivi.write(nomev+ " " + compleannov + " " + areav + "\n");
            
        } catch (IOException ex) {
            Logger.getLogger(profilo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
        new settings().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new settings().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itaActionPerformed
        // TODO add your handling code here:
         nomev = JOptionPane.showInputDialog(this,"Inserisci il tuo nome","Nome",2);
        nome.setText(nomev);
        
    }//GEN-LAST:event_itaActionPerformed

    private void engActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engActionPerformed
        // TODO add your handling code here:
         compleannov = JOptionPane.showInputDialog(this,"quando è il tuo compleanno?","Compleanno",2);
        compleanno.setText(compleannov);
    }//GEN-LAST:event_engActionPerformed

    private void deuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deuActionPerformed

    private void deu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deu1ActionPerformed
        // TODO add your handling code here:
         areav = JOptionPane.showInputDialog(this,"in che stato abiti?","Area",2);
        area.setText(areav);
    }//GEN-LAST:event_deu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profilo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area;
    private javax.swing.JLabel compleanno;
    private javax.swing.JButton deu;
    private javax.swing.JButton deu1;
    private javax.swing.JButton eng;
    private javax.swing.JButton ita;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
