/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocofinal;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andrea
 */
public class scegliPokemon extends javax.swing.JFrame {

    /**
     * Creates new form scegliPokemon
     */
    public scegliPokemon() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
            Scanner scan = new Scanner (new File ("usati.txt"));
            while (scan.hasNextLine()) {
                String linea = scan.nextLine();
                int tmp = Integer.parseInt(linea);
                if (tmp == 1) {
                    jButton3.setEnabled(false);
                } else if (tmp == 2) {
                    jButton4.setEnabled(false);
                } else if (tmp == 3) {
                    jButton5.setEnabled(false);
                } else if (tmp == 4) {
                    jButton2.setEnabled(false);
                } else if (tmp == 5) {
                    jButton7.setEnabled(false);
                } else if (tmp == 6) {
                    jButton6.setEnabled(false);
                }
            }
        } catch (IOException ex) {
                        Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pk4 = new javax.swing.JLabel();
        pk5 = new javax.swing.JLabel();
        pk6 = new javax.swing.JLabel();
        pk3 = new javax.swing.JLabel();
        pk2 = new javax.swing.JLabel();
        pk1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 770));
        setPreferredSize(new java.awt.Dimension(700, 770));
        setSize(new java.awt.Dimension(700, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/zeraora-scelta.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/dragonite-scelta.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 630, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/blastoise-scelta.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 50, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/charizard-scelta.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/pikachu-scelta.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/garchomp-scelta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        pk4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        pk4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pk4.setText("Charizard");
        getContentPane().add(pk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 160, 30));

        pk5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        pk5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pk5.setText("Blastoise");
        getContentPane().add(pk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 170, 30));

        pk6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        pk6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pk6.setText("Dragonite");
        getContentPane().add(pk6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 180, 50));

        pk3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        pk3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pk3.setText("Zeraora");
        getContentPane().add(pk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 180, 50));

        pk2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        pk2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pk2.setText("Pikachu");
        getContentPane().add(pk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 170, 30));

        pk1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        pk1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pk1.setText("Garchomp");
        getContentPane().add(pk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sceglipokemon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/indietro.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 660, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sceltaclean.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sceltaclean.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sceltaclean.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sceltaclean.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sceltaclean.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sceltaclean.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sfondoscelta.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocofinal/sfondosu.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void resettavita() {
        try(FileWriter scrivi = new FileWriter ("vita.txt")) {
                   
                    
                            scrivi.write("100");
                    } catch (IOException ex) {
                        Logger.getLogger(borsa.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try (FileWriter scrivi = new FileWriter ("selected.txt")) {
            scrivi.write(pk1.getText());
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        resettavita();
        
        try (FileWriter scrivi = new FileWriter ("usati.txt",true)) {
            scrivi.write("1\n");
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try (FileWriter scrivi = new FileWriter ("selected.txt")) {
            scrivi.write(pk2.getText());
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        resettavita();
        try (FileWriter scrivi = new FileWriter ("usati.txt",true)) {
            scrivi.write("2\n");
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try (FileWriter scrivi = new FileWriter ("selected.txt")) {
            scrivi.write(pk3.getText());
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        resettavita();
        try (FileWriter scrivi = new FileWriter ("usati.txt",true)) {
            scrivi.write("3\n");
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try (FileWriter scrivi = new FileWriter ("selected.txt")) {
            scrivi.write(pk4.getText());
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        resettavita();
        try (FileWriter scrivi = new FileWriter ("usati.txt",true)) {
            scrivi.write("4\n");
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try (FileWriter scrivi = new FileWriter ("selected.txt")) {
            scrivi.write(pk5.getText());
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        resettavita();
        try (FileWriter scrivi = new FileWriter ("usati.txt",true)) {
            scrivi.write("5\n");
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try (FileWriter scrivi = new FileWriter ("selected.txt")) {
            scrivi.write(pk6.getText());
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        resettavita();
        try (FileWriter scrivi = new FileWriter ("usati.txt",true)) {
            scrivi.write("6\n");
        } catch (IOException ex) {
            Logger.getLogger(scegliPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new gioc().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scegliPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scegliPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scegliPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scegliPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scegliPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel pk1;
    private javax.swing.JLabel pk2;
    private javax.swing.JLabel pk3;
    private javax.swing.JLabel pk4;
    private javax.swing.JLabel pk5;
    private javax.swing.JLabel pk6;
    // End of variables declaration//GEN-END:variables
}
